### PR TITLE
Expose as a module

### PR DESCRIPTION
**Pull request by hunterloftis**
barkeep in two flavours:

cli:

```
$ ../node_modules/.bin/barkeep
Listening at http://localhost:9000
Added: /index.html to list of watched files
Added: /test.js to list of watched files
Added: /test.map to list of watched files
```

or api:

``` js
var root = __dirname; // serve files from here
var sp = 9000;            // optional static port
var lp = 35729;           // optional livereload port

var server = barkeep(root).listen(sp, lp, onListen);

// optional callback
function onListen() {
  console.log('listening');
}
```

### CODE REVIEW

**Comment by jmorrell** [comment]
Is it bad that I feel weird not having to :+1: this and wait to merge it?

**Comment by hunterloftis** [comment]
Ha! Could you publish this on npm so I can update webpack-server?

**Comment by jmorrell** [comment]
I was going to add command line options and make it work on non-localhost first. Can it wait until tomorrow?

**Comment by hunterloftis** [comment]
For sure, just let me know. Whenever it's published I'm going to update webpack-server so we can get livereload on our react components (without all my local npm links!)

**Pull request merged**
